import { createActions } from "reduxsauce"

export const { Types, Creators } = createActions({
  addFavorites: ["favorite"],
  addWarnings: null,
  delFavorites: ["favorite"],
  delWarnings: null,
  getConfigs: null,
  getFavorites: null,
  getWarnings: null,
  getWeek: null,
  initOneSignal: null,
  requestWeek: null,
  setAction: ["action"],
  setAcceptedNotification: ["accepted"],
  setConfigs: ["configs"],
  setDay: ["day"],
  setFavorites: ["favorites"],
  setHomeView: ["homeView"],
  setIsOnBoarded: ["isOnBoarded"],
  setIsRequesting: ["isRequesting"],
  setNewWarning: ["newWarning"],
  setQuestions: ["questions"],
  setWarnings: ["warnings"],
  setWeek: ["week"],
  updateConfig: ["configs"],
  updateWeek: null,
})

// addFavorites = "ADD_FAVORITES",
// addWarnings = "ADD_WARNINGS",
// delFavorites = "DEL_FAVORITES",
// delWarnings = "DEL_WARNINGS",
// getConfigs = "GET_CONFIGURATIONS",
// getFavorites = "GET_FAVORITES",
// getWeek = "GET_WEEK",
// getWarnings = "GET_WARNINGS",
// initOneSignal = "INIT_ONE_SIGNAL",
// requestWeek = "REQUEST_WEEK",
// setConfigs = "SET_CONFIGURATIONS",
// setFavorites = "SET_FAVORITES",
// setWeek = "SET_WEEK",
// setNewWarning = "SET_NEW_WARNING",
// setWarnings = "SET_WARNINGS",
// setIsRequesting = "SET_IS_REQUESTING",
// updateConfig = "UPDATE_CONFIG",
// updateWeek = "UPDATE_WEEK",
