export enum Keys {
  acceptedNotification = "@RUral:acceptedNotification",
  configuration = "@RUral:configuration",
  favorites = "@RUral:favorites",
  isOnboarded = "@RUral:isOnboarded",
  week = "@RUral:week",
  _oldWeek = "@weeks",
  newWarning = "@RUral:newWarning",
  questions = "@RUral:questions",
  warnings = "@RUral:warnings",
}

export enum Actions {
  addFavorites = "ADD_FAVORITES",
  addWarnings = "ADD_WARNINGS",
  delFavorites = "DEL_FAVORITES",
  delWarnings = "DEL_WARNINGS",
  getConfigs = "GET_CONFIGURATIONS",
  getFavorites = "GET_FAVORITES",
  getWeek = "GET_WEEK",
  getWarnings = "GET_WARNINGS",
  initOneSignal = "INIT_ONE_SIGNAL",
  requestWeek = "REQUEST_WEEK",
  setConfigs = "SET_CONFIGURATIONS",
  setFavorites = "SET_FAVORITES",
  setWeek = "SET_WEEK",
  setNewWarning = "SET_NEW_WARNING",
  setWarnings = "SET_WARNINGS",
  setIsRequesting = "SET_IS_REQUESTING",
  updateConfig = "UPDATE_CONFIG",
  updateWeek = "UPDATE_WEEK",
}
